mock_movies = [
    {
        "id": 1,
        "title": "Interstellar",
        "release_date": "2014-11-07",
        "rating": 8.7,
        "overview": "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    },
    {
        "id": 2,
        "title": "Inception",
        "release_date": "2010-07-16",
        "rating": 8.8,
        "overview": "A skilled thief enters people's dreams to steal secrets.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    },
    {
        "id": 3,
        "title": "The Dark Knight",
        "release_date": "2008-07-18",
        "rating": 9.0,
        "overview": "Batman faces the Joker, who wants to plunge Gotham into chaos.",
        "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    },
    {
        "id": 4,
        "title": "Avatar",
        "release_date": "2009-12-18",
        "rating": 7.9,
        "overview": "A marine is sent to Pandora on a unique mission.",
        "poster_url": "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    },
    {
        "id": 5,
        "title": "Oppenheimer",
        "release_date": "2023-07-21",
        "rating": 8.4,
        "overview": "The story of J. Robert Oppenheimer and the Manhattan Project.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
    },
    {
        "id": 6,
        "title": "Dune",
        "release_date": "2021-10-22",
        "rating": 8.0,
        "overview": "Paul Atreides travels to the most dangerous planet in the universe.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    },
]